export const SELECCIONAR_CLIENTE = 'SELECCIONAR CLIENTE';
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR PRODUCTO';
export const CANTIDAD_PRODUCTOS = 'CANTIDAD_PRODUCTOS';
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL';
